apiVersion: v2
name: bors-ng
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"

# GitHub users or organisations
maintainers:
  - name: "bors-ng"

dependencies:
- name: postgresql
  condition: postgresql.enabled
  version: "10.3.14"
  repository: https://charts.bitnami.com/bitnami
